### PR TITLE
fix logging and compile issues

### PR DESCRIPTION
**Pull request by bassam**
Fixed numerous compile issues with logging and errors. Also added strgazer_cache to .gitignore.

Addresses #5

### CODE REVIEW

**Comment by bassam** [comment]
@spencerkimball can you please take a quick look?

**Comment by spencerkimball** [comment]
@bassam thank you so much for these updates. I hate to ask, but is there any way you could just remove the dependency on CockroachDB entirely and just simplify by using Go's base `log` package?

**Comment by bassam** [comment]
@spencerkimball ha! I started there and should've checked with you first. ok no prob.

**Comment by bassam** [comment]
@spencerkimball note that we lose info, warn and error levels. you also lose color support I believe. do you care?

**Comment by spencerkimball** [comment]
No, logging for this isn't so busy those features are critical.

**Comment by bassam** [comment]
@spencerkimball final had a chance to update this. let me know if you have any issues with it.

**Comment by spencerkimball** [comment]
Awesome. Thank you! I'll merge it now.

**Pull request merged**
